version: '3.8'

services:
  wordpress:
    build: .  # Dockerfileを使用してイメージをビルド
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wp_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest  # MySQLの代わりにMariaDBを使用（Apple Silicon対応）
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest  # Apple Siliconに対応するphpMyAdminのイメージ
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"

volumes:
  wp_data:
  db_data: